### ISSUE TITLE
use from esy/nix/opam

### ISSUE THREAD

**Issue by joprice** [anmonteiro/aws-lambda-ocaml-runtime#53]
I'd like to try this out, but unsure about a way to add it as a dependency. I'd be fine using esy nix or opam to install it, but I'm not good enough at any of them to figure out immediately how to go about that.

**Comment by anmonteiro** [comment]
There are opam files in this repo that list the dependencies and pins necessary to run this project:

https://github.com/anmonteiro/aws-lambda-ocaml-runtime/blob/4b22f63686eb65f0f7a33d20f9392449dedb68d4/lambda-runtime.opam#L23-L31

I haven't used opam in a bit, but if I recall correctly you just need to pin them like so:

```shell
$ opam pin add lambda-runtime git+https://github.com/anmonteiro/aws-lambda-ocaml-runtime
```

and if you want the Zeit Now package:

```shell
$ opam pin add now git+https://github.com/anmonteiro/aws-lambda-ocaml-runtime
```

Happy to give you more pointers if those aren't enough. Feel free to DM me in the Reason Discord too.
