### ISSUE TITLE
Best way to include in project?

### ISSUE THREAD

**Issue by gf3** [anmonteiro/aws-lambda-ocaml-runtime#58]
hi @anmonteiro, looking forward to using this library. what's the best way to include this library in my project as i don't see it published on opam?

**Comment by anmonteiro** [comment]
Hey!

This library used to rely on unreleased packages, but that's not the case anymore. We should be able to release to opam soon, thanks for the reminder.

In the meantime, if you're using OPAM you can just install it with `opam pin add lambda-runtime git+https://github.com/anmonteiro/aws-lambda-ocaml-runtime`

**Comment by gf3** [comment]
@anmonteiro awesome thank you! i’m pretty new to the ocaml ecosystem; is there a way to pin lambda-runtime via the dune-project file or opam file if i intend to share my project with others?

**Comment by anmonteiro** [comment]
> is there a way to pin lambda-runtime via the dune-project file or opam file if i intend to share my project with others

The only way that I know is by using [`pin-depends`](https://opam.ocaml.org/doc/Manual.html#opamfield-pin-depends) but these fields are [not transitive](https://github.com/ocaml/opam/issues/4003).

In any case, I just submitted a release to OPAM. You can follow it here: https://github.com/ocaml/opam-repository/pull/18524. I'll close this issue once the packages have been released.

**Comment by gf3** [comment]
cheers, thanks 🙏
